apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mywp.fullname" . }}-efs-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: {{.Values.deployment.efs_storage_class}}
spec:
  storageClassName: {{.Values.deployment.efs_storage_class}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi